### ISSUE TITLE
Alterar cores para o darkmode do linkedin

### ISSUE THREAD

**Issue by raafaelgomees10** [leapfrogworks/feedback#2]
## 🐛 Bug Report

- **Description**: As cores não se aplicam à versão darkmode do LinkedIn
- **Expected Behavior**: Devia ser possível alterar as cores de acordo com o tema do LinkedIn
- **Screenshots**:
![image](https://github.com/user-attachments/assets/9c1a4b93-8b0c-4afb-950d-981eb645fd0f)

- **Device/Browser Info**:  Chrome

## 💡 Feature Request

- **Description**: Apenas trocar a cor do background e do texto quando o linkedin estiver no darkmode
- **Why It Matters**: Facilitaria a leitura, sem a necessidade de passar o cursor por cima

**Comment by felipedaraujo** [comment]
@raafaelgomees10 , obrigado pelo feedback, cara! Acabei de corrigir esse problema. Vou publicar uma nova versão com a correção nesse final de semana.

**Comment by felipedaraujo** [comment]
@raafaelgomees10 , a versão 2.3.2 está no ar com a correção das cores para o dark mode. https://leapfrog.works/

Novamente, obrigado por me avisar sobre o problema.
