### ISSUE TITLE
Tags not showing

### ISSUE THREAD

**Issue by marcoaaguiar** [leapfrogworks/feedback#3]
## 🐛 Bug Report

- **Description**: Tags are not showing
- **Steps to Reproduce**: 
  1. Go to [jobs page](https://www.linkedin.com/jobs/search/?currentJobId=4011745548&f_C=42640%2C6654288%2C583166%2C18625771%2C3650502%2C18664911&geoId=92000000&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true) (taken from Notion page)
  2. No tag shows in any job posting
- **Expected Behavior**: There should be tags in each/some of the job listings
- **Screenshots**: 
![image](https://github.com/user-attachments/assets/9e481549-5177-4c30-a88d-26cad42e76ff)

- **Device/Browser Info**: Chrome on Windows 11. Linkedin Premium, Language set to English. Correctly logged on extension

**Comment by felipedaraujo** [comment]
Mestre @marcoaaguiar , thanks for the report. I am looking into that and I will get back to you soon.

**Comment by marcoaaguiar** [comment]
If there is any other info that I can provide to help you solve this let me know

**Comment by mocha06** [comment]
Same issue here! Let me know if I can help @felipedaraujo

**Comment by felipedaraujo** [comment]
@marcoaaguiar , @mocha06 muito obrigado pela disposição em ajudar, camaradas.

Testei aqui em um Windows 11, LinkedIn Premium, mas não consegui replicar o erro.

Vocês podem me fazer um favor.
1. Naveguem até chrome://extensions.
2. Ativa **Developer mode**
3. Clica em **service worker** e deixa essa nova janela aberta.
4. Dentro dessa nova janela, clica em **Network**
![image](https://github.com/user-attachments/assets/0a46b657-c390-442d-b481-f713a3a45fee)
5. Vai até https://www.linkedin.com/jobs/collections/recommended/
6. Abre o Dev Tools Console (Shift + CTRL + J)
7. Clica em errors na coluna esquerda.
8. Salva os errors e compartilha aqui comigo, por gentileza.
<img width="1706" alt="Screenshot 2024-10-03 at 11 15 56 AM" src="https://github.com/user-attachments/assets/869c2ac4-59f0-425e-990e-01e26940d4a2">
9. Por fim, volta lá naquela outra janela Dev Tools Console que abriu depois de clicarmos **service worker**. Tira um screenshot da janela **Network**, por favor, e também compartilha comigo.

Mais uma vez obrigado por se importarem em ajudar 🙌 🕺

**Comment by mocha06** [comment]
Not sure what's been changed (maybe on the browser's side, or maybe an intermittent bug), but it's working again:

![image](https://github.com/user-attachments/assets/110c17cb-46f3-4417-a9e1-43a612b1a060)

**Comment by felipedaraujo** [comment]
> Not sure what's been changed (maybe on the browser's side, or maybe an intermittent bug), but it's working again:

That is awesome. I have made some code changes to try to address the issue. Let me know if you see any problems again.

**Comment by fhmurakami** [comment]
Hi @felipedaraujo, I'm having this same issue. As you can see in the image below.

![Captura de tela 2024-11-08 001540](https://github.com/user-attachments/assets/aa7f50cc-b7ad-4ba8-9311-8ec6913a7e69)

My configs are:
- Windows 11
- Chrome (Version 130.0.6723.117 (Official build) (64-bit))
- I tried on Edge too (Version 130.0.2849.68 (Official build) (64-bit))

Here is the errors log and the Network tab screenshot:
[www.linkedin.com-1731035148046.log](https://github.com/user-attachments/files/17672128/www.linkedin.com-1731035148046.log)

![Captura de tela 2024-11-08 000701](https://github.com/user-attachments/assets/dd94e149-de5d-4884-a646-d925896b80ea)

Let me know if you need any other info.

**Comment by felipedaraujo** [comment]
@fhmurakami, I know this has been forever and you probably gave up from using the tool, but were you ever able to see it working?

**Comment by fhmurakami** [comment]
Yes, it's working! :)
