### ISSUE TITLE
the extension didnt work here

### ISSUE THREAD

**Issue by najibe1** [leapfrogworks/feedback#4]
## 🐛 Bug Report

- **Description**: The extension didnt work here, is my linkedin account?
- **Steps to Reproduce**: 
  1. 
  2. 
- **Expected Behavior**: The extension works
- **Screenshots**: 
- **Device/Browser Info**: Mac

<img width="1382" alt="Screenshot 2024-11-23 at 10 15 49" src="https://github.com/user-attachments/assets/370d7bec-9a41-4f0c-8709-f3f3456c2faf">

**Comment by felipedaraujo** [comment]
@najibe1 , obrigado por me avisar sobre esse erro. Acabei de enviar uma correção e a extensão deve estar funcionando novamente. Boa sorte e qualquer outro problema, estarei a disposição.

![Screenshot 2024-11-24 at 3 43 17 PM](https://github.com/user-attachments/assets/6ef8e1ad-5545-4591-a472-13042fa8ee31)
