### ISSUE TITLE
Extension doesn't work on the 

### ISSUE THREAD

**Issue by Andy9822** [leapfrogworks/feedback#5]
## 🚨 Before You Post

**Search first**: Please check if an issue already exists before creating a new one. Upvote or comment on similar issues to help us prioritize.

## 🐛 Bug Report

- **Description**: What’s the bug?
- **Steps to Reproduce**: 
  1. 
  2. 
- **Expected Behavior**: What should happen?
- **Screenshots**: (If applicable)
- **Device/Browser Info**: (e.g., Chrome on Mac)

## 💡 Feature Request

- **Description**: What’s your suggestion or feature request?
- **Why It Matters**: How would this improve your experience?

---

**Check for existing issues**: [Search issues](https://github.com/leapfrogworks/feedback/issues) before posting.

**Comment by felipedaraujo** [comment]
Hey @Andy9822 , I see you filled [another issue](https://github.com/leapfrogworks/feedback/issues/6), so I'm closing this one. Thanks for your help, man.
