### ISSUE TITLE
Extension doesn't work on the "Top job picks for you" page

### ISSUE THREAD

**Issue by Andy9822** [leapfrogworks/feedback#6]
I just installed the extension and it does work correctly on the regular search jobs page:

![image](https://github.com/user-attachments/assets/9ede966d-a6b6-459e-a354-50276e1f403e)

However, if you access https://www.linkedin.com/jobs/ Linkedin may suggest you some jobs that match with your profile and preferences. If you click on it, you get redirected to a  https://www.linkedin.com/jobs/collections/recommended/ URL where the extension DOES NOT work:

![image](https://github.com/user-attachments/assets/64488042-9cc6-4f9b-a758-1d8f96d0e53c)

I believe it comes down to the fact the extension is either trying to match the URL or searching for a specific div that can't be encountered on this page even though the rest of the webpage looks exactly the same as the regular jobs one

**Comment by felipedaraujo** [comment]
Hey @Andy9822 , thank you so much for reporting that issue. I will look into that and get back to you later this weekend.

**Comment by felipedaraujo** [comment]
Hey @Andy9822 , could double check? Since you posted this issue, I release version 2.4.0 with some fixes. So, it may be working now.

<img width="1079" alt="Screenshot 2024-12-05 at 9 22 01 PM" src="https://github.com/user-attachments/assets/5c4dad93-cc22-4a46-be82-ab7f70c7eedc">

**Comment by Andy9822** [comment]
> Hey @Andy9822 , could double check? Since you posted this issue, I release version 2.4.0 with some fixes. So, it may be working now.
> 
> <img alt="Screenshot 2024-12-05 at 9 22 01 PM" width="1079" src="https://private-user-images.githubusercontent.com/1224072/393068415-5c4dad93-cc22-4a46-be82-ab7f70c7eedc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNDM5MjksIm5iZiI6MTczNDA0MzYyOSwicGF0aCI6Ii8xMjI0MDcyLzM5MzA2ODQxNS01YzRkYWQ5My1jYzIyLTRhNDYtYmU4Mi1hYjdmNzBjN2VlZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMjI0NzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDgwODdhMDQxMzdkZjZlYjFhOGQ2Yzg4NjRlM2U4ZGYzMjRmM2ZlYTdiNjlkODZlM2I3NjQ3ODNjOTI2YjdhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0f-ZZFU0Qb4eB0JWPeOdxcXQZmoXfuKy51crmButlFs">

It's working now!!! Ty'
